### ISSUE TITLE
Angular code snippets

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/docs#369]

**Comment by jscyo** [comment]
Feedback:
- [ ] Certain sections in docs for angular snippets require both SDK(session related changes)
- [ ] Change ` Setup the login UI` -> `Setup Routing to show the login UI`
- [ ] Move the angular routing snippet to `Setup Routing to show the login UI`
- [ ] Copy changes for Custom UI in routing -> "You will have to manage routing yourself since you are using custom UI."
