### ISSUE TITLE
Typo in doc ?

### ISSUE THREAD

**Issue by Cajuteq** [supertokens/docs#666]
I am quite new to supertokens, so maybe it's just incomprehension, but while reading

https://github.com/supertokens/docs/blob/master/v2/phonepassword/backend/session-customisation.mdx

I found this line
![image](https://github.com/supertokens/docs/assets/26676532/5beee927-052e-4c98-99a7-9c7ef6af5e71)

And found it weird to put "email" in "phoneNumber"

**Comment by rishabhpoddar** [comment]
Yea, this guide shows you how to customise the email password recipe to work with phone & passwords. This type of customisation is a little strange, but it's the only solution given that we don't have a native phone & password recipe.

Since this is not a mistake in the docs, I'm closing this issue.
